import Head from "next/head";
import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import Home from "./home";
import Input from "../components/form/Input";

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <div className="container p-20 mx-auto">
        <Input />
      </div>
      <Footer />
    </>
  );
}
